### ISSUE TITLE
[Problem] Signup POST error

### ISSUE THREAD

**Issue by njs03332** [JW275/SWPP2018_01_Group15_BackEnd#10]
still having trouble with signup

POST http://127.0.0.1:8000/signup/ 400 (Bad Request)
sagas.js:84 Error: 400 Bad Request
    at checkStatus (index.js:10)

this is my error message.
Nooooooo idea why I can't sign up... any guesses?

**Comment by munjinoo** [comment]
입력한 data는 어떻게 되나요?

**Comment by munjinoo** [comment]
solved
