### ISSUE TITLE
[Problem] Backend jquery version error?

### ISSUE THREAD

**Issue by njs03332** [JW275/SWPP2018_01_Group15_BackEnd#9]
나 백엔드 runserver해서 돌리면 모든 url이 창은 뜨는데 console에 
jQuery.Deferred exception: e.indexOf is not a function TypeError: e.indexOf is not a function
이런 에러가 떠!!
구글링 해보니까 jquery 버전 incompatible 이런 말 나오는데 진짜 이게 문제인걸까...?
무엇이 문제인지 모르겠다..
헬프미

**Comment by munjinoo** [comment]
장고에서 api를 보기편하게 보여주기 위해 jqeury가 쓰이는것이고 아마 버젼문제인 듯 싶으나
frontend쪽에서 api를 받아올때와 사용시에 큰 문제가 없어서 무시하고 진행해도 될듯
